# UsableNet AQA Browser - stand-in MCP server for a Windows machine without Node.js.
#
# Generated by build.mjs from packages/mcp/launcher/aqa-mcp.ps1; edit the
# template, not this copy. Run by aqa-mcp.cmd when it finds no Node.js
# 20+: prints the install steps to stderr (the host's MCP log)
# and then speaks just enough MCP over stdio for the host to connect and list
# one tool, aqa_setup_bridge, which returns those steps so the agent can
# relay them to a user who never opens a command line.
param(
  [string]$Found = '',
  [string]$FoundVersion = ''
)

$ErrorActionPreference = 'Stop'
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)
$log = '[UsableNet AQA Browser launcher]'
$minMajor = 20

function Write-Log([string]$Message) {
  [Console]::Error.WriteLine("$log $Message")
}

$steps = @'
["Open https://nodejs.org/en/download in your browser and click the Windows Installer (.msi) for the LTS version - no command line needed.","Run the downloaded .msi and click Next through the installer, keeping the default options (Add to PATH stays checked).","Then fully quit and reopen the app you use the agent in (Claude Code, Cursor, the Codex app, VS Code, ...) - it only sees Node.js after a restart.","If Node.js is already installed (nvm-windows, Volta) and still not found, set the AQA_NODE environment variable of the MCP server to the full path of node.exe."]
'@ | ConvertFrom-Json

if ($Found) {
  $diagnosis = 'node-too-old'
  $found = @{ path = $Found; version = $FoundVersion }
  Write-Log "Node.js $FoundVersion at $Found is too old - UsableNet AQA Browser needs Node.js $minMajor or newer."
} else {
  $diagnosis = 'node-missing'
  $found = $null
  Write-Log "Node.js was not found on this machine (not on PATH, not in the usual install folders) - UsableNet AQA Browser needs Node.js $minMajor or newer."
}
Write-Log 'The AQA tools stay unavailable until it is installed. Steps:'
for ($i = 0; $i -lt $steps.Count; $i += 1) { Write-Log ("  {0}. {1}" -f ($i + 1), $steps[$i]) }

$result = @{
  ok = $false
  diagnosis = $diagnosis
  found = $found
  required = "Node.js $minMajor or newer"
  steps = $steps
  note = 'After installing Node.js, fully quit and reopen the app that runs this agent; the AQA tools appear on its next start. Nothing else is wrong: the Chrome extension and the pairing are checked only once the server itself runs.'
} | ConvertTo-Json -Compress -Depth 5

$instructions = @'
"Node.js is not available on this machine, so the UsableNet AQA Browser tools cannot run yet. The one tool here, aqa_setup_bridge, returns the install steps: call it and relay the steps to the user in plain language — they may never use a terminal. Once Node.js is installed the user must fully quit and reopen this app; the real tools appear on its next start."
'@ | ConvertFrom-Json
$toolDescription = @'
"Reports why the UsableNet AQA Browser tools are unavailable on this machine (Node.js missing or too old) and returns step-by-step install instructions written for a non-technical user. Call it whenever the user asks for AQA or accessibility checks, or asks why the tools are missing."
'@ | ConvertFrom-Json
$serverName = @'
"UsableNet AQA Browser"
'@ | ConvertFrom-Json

function Send-Reply($Object) {
  [Console]::Out.WriteLine(($Object | ConvertTo-Json -Compress -Depth 8))
}

$protocol = '2024-11-05'
while ($null -ne ($line = [Console]::In.ReadLine())) {
  if ($line.Trim().Length -eq 0) { continue }
  try { $request = $line | ConvertFrom-Json } catch { continue }
  $method = [string]$request.method
  $hasId = $null -ne $request.PSObject.Properties['id']
  switch ($method) {
    'initialize' {
      if ($request.params -and $request.params.protocolVersion) { $protocol = [string]$request.params.protocolVersion }
      Send-Reply @{ jsonrpc = '2.0'; id = $request.id; result = @{
        protocolVersion = $protocol
        capabilities = @{ tools = @{} }
        serverInfo = @{ name = $serverName; version = '0.3.3' }
        instructions = $instructions
      } }
    }
    'tools/list' {
      Send-Reply @{ jsonrpc = '2.0'; id = $request.id; result = @{ tools = @(
        @{ name = 'aqa_setup_bridge'; description = $toolDescription; inputSchema = @{ type = 'object'; properties = @{} } }
      ) } }
    }
    'tools/call' {
      Send-Reply @{ jsonrpc = '2.0'; id = $request.id; result = @{ content = @(@{ type = 'text'; text = $result }) } }
    }
    'ping' {
      Send-Reply @{ jsonrpc = '2.0'; id = $request.id; result = @{} }
    }
    default {
      if ($hasId -and -not $method.StartsWith('notifications/')) {
        Send-Reply @{ jsonrpc = '2.0'; id = $request.id; error = @{ code = -32601; message = "Method not found: $method - this stand-in only reports that Node.js is missing" } }
      }
    }
  }
}
