@echo off
rem UsableNet AQA Browser - MCP server launcher (Windows).
rem
rem Generated by build.mjs from packages/mcp/launcher/aqa-mcp.cmd; edit the
rem template, not this copy. Same contract as the POSIX launcher next to it:
rem finds a Node.js 20+ (AQA_NODE, PATH, then the folders the
rem installers use) and runs mcp-server.js with it, with the same arguments
rem and stdio. Without one, aqa-mcp.ps1 prints the install steps and stands in
rem for the server so the agent can relay them. Not verified on a Windows host
rem yet: hosts resolve the extensionless command to this file through PATHEXT
rem (the MCP TypeScript SDK's stdio client does, via cross-spawn) and run it
rem with cmd.exe.
setlocal EnableExtensions
set "MIN_MAJOR=20"
set "HERE=%~dp0"
for %%I in ("%HERE%..") do set "ROOT=%%~fI"
set "SERVER=%ROOT%\mcp-server.js"
set "NODE="
set "FOUND="
set "FOUND_VERSION="

if defined AQA_NODE call :try "%AQA_NODE%"
if not defined NODE for /f "delims=" %%P in ('where node 2^>nul') do if not defined NODE call :try "%%P"
if not defined NODE if "%AQA_NODE_NO_SEARCH%"=="1" goto :standin
if not defined NODE call :try "%ProgramFiles%\nodejs\node.exe"
if not defined NODE if defined ProgramFiles(x86) call :try "%ProgramFiles(x86)%\nodejs\node.exe"
if not defined NODE call :try "%LOCALAPPDATA%\Programs\nodejs\node.exe"
if not defined NODE if defined NVM_SYMLINK call :try "%NVM_SYMLINK%\node.exe"
if not defined NODE call :try "%LOCALAPPDATA%\Volta\bin\node.exe"
if not defined NODE call :try "%APPDATA%\fnm\aliases\default\node.exe"

:standin
if defined NODE (
  "%NODE%" "%SERVER%" %*
  exit /b %ERRORLEVEL%
)
powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -File "%HERE%aqa-mcp.ps1" -Found "%FOUND%" -FoundVersion "%FOUND_VERSION%"
exit /b %ERRORLEVEL%

rem try <path> - sets NODE when the executable exists and is new enough;
rem remembers the newest too-old one in FOUND / FOUND_VERSION.
:try
if not exist "%~1" exit /b 0
set "VER="
for /f "usebackq delims=" %%V in (`"%~1" -v 2^>nul`) do set "VER=%%V"
if not defined VER exit /b 0
set "MAJOR=%VER:~1%"
for /f "tokens=1 delims=." %%M in ("%MAJOR%") do set "MAJOR=%%M"
if %MAJOR% GEQ %MIN_MAJOR% (
  set "NODE=%~1"
) else (
  set "FOUND=%~1"
  set "FOUND_VERSION=%VER%"
)
exit /b 0
